###############################################################################
PROJECT         = <name>

LIB_DIR         = <local geda-lib path>

GEDATOOLS_DIR   = <geda-tools path>
GEDALIB_DIR     = <geda-lib path>

COND_DEFS       = <defines for cond.rb>

###############################################################################
include $(GEDATOOLS_DIR)make/gedaflow-defaults.mk
include $(GEDATOOLS_DIR)make/gedaflow.mk
